ShopAcc/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ShopAcc.Models;
using ShopAcc.Mail;
using Newtonsoft.Json.Linq;
using ShopAcc.MoMo;
using System.Configuration;

namespace ShopAcc.Controllers
{
    public class CartController : Controller
    {
        // GET: Cart
        MyDataDataContext data = new MyDataDataContext();
        public List<GioHang> Laygiohang()
        {

            List<GioHang> lstGiohang = new List<GioHang>();
            User user = (User)Session["TaiKhoan"];
            var truycap = data.TruyCaps.Where(p => p.iduser == user.iduser && p.Account.trangthai==true);
            foreach (var item in truycap)
            {
                GioHang sanpham = new GioHang(item.id);
                lstGiohang.Add(sanpham);
            }
            ViewBag.Tongsoluong = lstGiohang.Count;
            ViewBag.Tongtien = lstGiohang.Sum(n => n.giaban);
            return lstGiohang;
        }
        public ActionResult ThemGioHang(int id, string strURL)
        {
            User user = (User)Session["TaiKhoan"];
            var acc = data.TruyCaps.Where(p => p.id == id && p.iduser ==user.iduser).FirstOrDefault();
            if (acc == null)
            {
                List<GioHang> lstGiohang = new List<GioHang>();
                TruyCap truyCap = new TruyCap();
                truyCap.iduser = user.iduser;
                truyCap.id = id;
                truyCap.trangthai = true;
                data.TruyCaps.InsertOnSubmit(truyCap);
                data.SubmitChanges();
                return Redirect(strURL);
            }
            else
                return Redirect(strURL);
        }
       
        public ActionResult GioHang()
        {
            List<GioHang> lstGiohang = Laygiohang();
            ViewBag.Tongsoluong = lstGiohang.Count;
            ViewBag.Tongtien = lstGiohang.Sum(n => n.giaban);
            return View(lstGiohang);
        }
        public ActionResult GioHangPartial()
        {
            return PartialView();
        }
        public ActionResult XoaAcc(int id)
        {
            List<GioHang> lstGiohang = Laygiohang();
            User user = (User)Session["TaiKhoan"];
            var truycap = data.TruyCaps.Where(p => p.id == id && p.iduser==user.iduser).First();
            if (truycap != null)
            {
                data.TruyCaps.DeleteOnSubmit(truycap);
                data.SubmitChanges();
            }

            return RedirectToAction("GioHang");

        }
        public ActionResult XoaAll()
        {

            User user = (User)Session["TaiKhoan"];

            var truycap = data.TruyCaps.Where(p => p.iduser == user.iduser);
            foreach (var item in truycap)
            {
                data.TruyCaps.DeleteOnSubmit(item);
            }
            data.SubmitChanges();

            return RedirectToAction("GioHang");
        }



        [HttpGet]
        public ActionResult DatHang()
        {
            List<GioHang> lstGiohang = Laygiohang();
            ViewBag.Tongsoluong = lstGiohang.Count;
            ViewBag.Tongtien = lstGiohang.Sum(n => n.giaban);
            if (lstGiohang == null )
            {
                return RedirectToAction("HomePage", "Account");
            }
           
            return View(lstGiohang);
        }
       
        //public ActionResult Payment()
        //{
        //    var lstGioHang = Laygiohang();
        //    User user = (User)Session["TaiKhoan"];
        //    var total = lstGioHang.Sum(n => n.giaban);

        //     string detail = "";

        //    foreach (var item in lstGioHang)
        //    {
        //        detail += "Tài khoản:  " + item.taikhoan.ToString() + "" + "Mật khẩu:  " + item.matkhau.ToString() + "=======================";
                
        //    }

        //    string content = System.IO.File.ReadAllText(Server.MapPath("~/content/template/neworder.html"))+detail;

        //    content = content.Replace("{{CustomerName}}", user.tenhienthi);
        //    content = content.Replace("{{Phone}}", user.sdt);
        //    content = content.Replace("{{Email}}", user.email);
        //    content = content.Replace("{{Address}}", user.anhdaidien);
        //    content = content.Replace("{{Total}}", total.ToString("N0"));
        //    var toEmail = ConfigurationManager.AppSettings["ToEmailAddress"].ToString();

            
        //    new MailHelper().SendEmail(user.email, "Xác nhận mua Acc", content);
        //    new MailHelper().SendEmail(toEmail, "Xác nhận mua Acc", content);
        //    return RedirectToAction("GioHang");

        //}
        //public ActionResult Payment()
        //{
        //    var lstGioHang = Laygiohang();
        //    User user = (User)Session["TaiKhoan"];
        //    var total = lstGioHang.Sum(n => n.giaban);

        //    string detail = "";

        //    foreach (var item in lstGioHang)
        //    {
        //        detail += "Tài khoản:  " + item.taikhoan.ToString() + "" + "Mật khẩu:  " + item.matkhau.ToString() + "=======================";

        //    }

        //    string content = System.IO.File.ReadAllText(Server.MapPath("~/content/template/neworder.html")) + detail;


        //    var hoadon = new HoaDon();
        //    hoadon.ngaythanhtoan = DateTime.Today;
        //    hoadon.thanhtoan = false;
        //    hoadon.tongtien = (Decimal)total;
        //    try
        //    {
        //        data.HoaDons.InsertOnSubmit(hoadon);
        //        data.SubmitChanges();

        //        foreach (var item in lstGioHang)
        //        {
        //            var cthd = new ChiTietHD();
        //            cthd.iduser = user.iduser;
        //            cthd.id = item.idacc;
        //            cthd.maHD = hoadon.maHD;
        //            cthd.gia = item.giaban;

        //            data.ChiTietHDs.InsertOnSubmit(cthd);
        //            data.SubmitChanges();
        //        }

        //        //var chitiet = data.ChiTietHDs.ToList();
        //        //var acc = data.Accounts.ToList();
        //        content = content.Replace("{{CustomerName}}", user.tenhienthi);
        //        content = content.Replace("{{Phone}}", user.sdt);
        //        content = content.Replace("{{Email}}", user.email);
        //        content = content.Replace("{{Total}}", hoadon.tongtien.ToString());
        //        foreach (var item in lstGioHang)
        //        {
        //            content = content.Replace("{{TaiKhoan}}", item.taikhoan);
        //            content = content.Replace("{{MatKhau}}", item.matkhau);
        //        }
        //        var toEmail = ConfigurationManager.AppSettings["ToEmailAddress"].ToString();


        //        new MailHelper().SendEmail(user.email, "Xác nhận mua Acc", content);
        //        new MailHelper().SendEmail(toEmail, "Xác nhận mua Acc", content);
        //    }
        //    catch (Exception)
        //    {
        //        return Redirect("/Cart/UnSuccess");
        //    }
        //    return Redirect("/Cart/Success");
        //}
        public ActionResult PaymentMoMo()
        {
            var lstGioHang = Laygiohang();
            User user = (User)Session["TaiKhoan"];
            var total = lstGioHang.Sum(n => n.giaban);

            string detail = "";

            foreach (var item in lstGioHang)
            {
                detail += "Tài khoản:  " + item.taikhoan.ToString() + "------" + "Mật khẩu:  " + item.matkhau.ToString() + "=======================";

            }

            string content = System.IO.File.ReadAllText(Server.MapPath("~/content/template/neworder.html")) + detail;
            foreach (var item in lstGioHang)
            {
                var acc = data.Accounts.Where(p => p.id == item.idacc).First();
                if(acc!= null)
                {
                    acc.trangthai = false;
                    UpdateModel(acc);
                    data.SubmitChanges();

                }    
            }
           

            
            data.SubmitChanges();
            var hoadon = new HoaDon();
            hoadon.ngaythanhtoan = DateTime.Today;
            hoadon.thanhtoan = true;
            hoadon.tongtien = (Decimal)total;
            try
            {
                data.HoaDons.InsertOnSubmit(hoadon);
                data.SubmitChanges();

                foreach (var item in lstGioHang)
                {
                    var cthd = new ChiTietHD();
                    cthd.iduser = user.iduser;
                    cthd.id = item.idacc;
                    cthd.maHD = hoadon.maHD;
                    cthd.gia = item.giaban;

                    data.ChiTietHDs.InsertOnSubmit(cthd);
                    data.SubmitChanges();

                }
               
                //var chitiet = data.ChiTietHDs.ToList();
                //var acc = data.Accounts.ToList();
                content = content.Replace("{{CustomerName}}", user.tenhienthi);
                content = content.Replace("{{Phone}}", user.sdt);
                content = content.Replace("{{Email}}", user.email);
                content = content.Replace("{{Total}}", hoadon.tongtien.ToString());
                foreach (var item in lstGioHang)
                {
                    content = content.Replace("{{TaiKhoan}}", item.taikhoan);
                    content = content.Replace("{{MatKhau}}", item.matkhau);
                }
                var toEmail = ConfigurationManager.AppSettings["ToEmailAddress"].ToString();


                new MailHelper().SendEmail(user.email, "Xác nhận mua Acc", content);
                new MailHelper().SendEmail(toEmail, "Xác nhận mua Acc", content);
                
            }

            catch (Exception)
            {
                return Redirect("/Cart/UnSuccess");
            }


            //request params need to request to MoMo system

ShopAcc/Controllers/GameController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ShopAcc.Models;

namespace ShopAcc.Controllers
{
    public class GameController : Controller
    {
        // GET: Game
        MyDataDataContext data = new MyDataDataContext();
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult LMHT()
        {
            var acc = data.Accounts.Where(p => p.idGame == 1 && p.trangthai == true).ToList();

            return View(acc);
        }
        public ActionResult TocChien()
        {
            var acc = data.Accounts.Where(p => p.idGame == 2 && p.trangthai == true).ToList();

            return View(acc);
        }
        public ActionResult LQM()
        {
            var acc = data.Accounts.Where(p => p.idGame == 3 && p.trangthai == true).ToList();

            return View(acc);
        }
    }
}

ShopAcc/Views/Shared/_Layout.cshtml
@{
    var User = Session["TaiKhoan"] as ShopAcc.Models.User;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />

    <title>ShopAcc</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <!-- Bootstrap icons-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="assets/css/style.css">
    <link href="~/Content/stylefooter.css" rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="~/Content/Style.css" rel="stylesheet" />
</head>
<body>
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container px-4 px-lg-5">
            @*<a class="navbar-brand" href="#!">ShopAcc</a>*@
            <img src="~/Content/images/LogoShop.jpg" width="120px" height="60px" alt="Logo Shop" />
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                    <li class="nav-item"><a class="nav-link active" aria-current="page" href="https://localhost:44355/Account/HomePage#!">Trang chủ</a></li>
                    <li class="nav-item"><a class="nav-link" href="https://localhost:44355/Home/Contact">Liên hệ</a></li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Tựa game</a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="@Url.Action("LMHT", "Game")">Liên Minh Huyền Thoại</a></li>
                            <li><hr class="dropdown-divider" /></li>
                            <li><a class="dropdown-item" href="@Url.Action("TocChien", "Game")">Tốc Chiến</a></li>
                            <li><hr class="dropdown-divider" /></li>
                            <li><a class="dropdown-item" href="@Url.Action("LQM", "Game")">Liên Quân Mobile</a></li>
                        </ul>
                    </li>
                    @if (User != null)

                    {
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("GioHang", "Cart")">
                                <i class="bi-cart-fill me-1"></i>
                                Giỏ hàng
                                <span class="badge bg-dark text-white ms-1 rounded-pill">@ViewBag.Tongsoluong</span>
                            </a>
                        </li>
                    }
                    else
                    {
                        //<li class="nav-item"><a class="nav-link" href="#!">Xin chào: @User.tendn</a></li>
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("DangNhap", "User")">
                                <i class="bi-cart-fill me-1"></i>
                                Giỏ hàng
                                <span class="badge bg-dark text-white ms-1 rounded-pill">@ViewBag.Tongsoluong</span>
                            </a>
                        </li>
                    }
                </ul>



                @if (User == null)

                {
                    <form class="d-flex">
                        <a href="@Url.Action("DangNhap", "User")">
                            <button class="btn btn-danger" type="button">
                                <i class="bi bi-person-circle"></i>
                                Đăng nhập
                            </button>
                        </a>
                    </form>

                    @*<li class="nav-item"><a class="nav-link" href="@Url.Action("DangNhap","User")">Đăng nhập</a></li>*@
                }
                else
                {

                    <form class="d-flex">
                        <a href="@Url.Action("DangXuat", "User")">
                            <button class="btn btn-danger" type="button">
                                <i class="bi bi-person-x-fill"></i>
                                Đăng Xuất
                            </button>
                        </a>
                    </form>
                    <form class="d-flex">
                        <a href="@Url.Action("Edit", "User", new { id = @User.iduser })">
                            <button class="btn btn-outline-primary" type="button">
                                <i class="bi bi-person-lines-fill"></i>
                                 @User.tendn
                            </button>
                        </a>
                    </form>
                    
                    @*<li class="nav-item"><a class="nav-link" href="@Url.Action("DangXuat","User")">Đăng xuất</a></li>*@

                }
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <div class="footer-dark">
            <footer>
                <div class="container">
                    <div class="row">
                        <div class="col-sm-6 col-md-3 item">
                            <h3 style="color:coral">&ensp;&emsp;<i class="bi bi-person-circle"></i> Morphine Deadline</h3>
                            <ul>
                                <li><h6 style="font-size:small">&emsp;&emsp;Nguyễn Bùi Hoàng Phước</hr></li>
                                <li><h6 style="font-size:small">&emsp;&emsp;Trần Thanh Phước</hr></li>
                                <li><h6 style="font-size:small">&emsp;&emsp;Lê Trọng Phước</hr></li>
                                <li><h6 style="font-size:small">&emsp;&emsp;Trần Hữu Quang</hr></li>
                            </ul>
                        </div>
                        <div class="col-sm-6 col-md-3 item">
                            <h3 style="color:coral">Liên Hệ:</h3>
                            <ul>
                                <li><h6 style="font-size:smaller"><i class="bi bi-envelope-fill"></i>&ensp; shopaccvng@gmail.com</hr></li>
                                <li><h6 style="font-size:smaller"><i class="bi bi-telephone-fill"></i>&ensp; 0788-988-797</hr></li>
                                <li style="font-size:large; color:deepskyblue">
                                    &emsp;&emsp;<a href="https://www.facebook.com/profile.php?id=100005414179219"><i class="icon ion-social-facebook"></i> </a>&ensp;<a href="#"><i class="icon ion-social-twitter"></i></a>&ensp;<a href="#"> </a><a href="#"><i class="icon ion-social-instagram"></i> </a>
                                </li>
                            </ul>
                        </div>
                        <div class="col-sm-6 col-md-6 item">
                            <div class="col-md-6 item text">
                                <h3 style="color:coral">HUTECH - Khoa CNTT</h3>
                                <p>Đồ án môn: Lập Trình Web</p>
                                <p>Giảng viên hướng dẫn: Trịnh Công Nhựt</p>
                                <p>Nhóm thực hiện: Nhóm 11</p>
                            </div>

                        </div>
                        @*<p class="copyright">Company Name © 2018</p>*@
                    </div>
            </footer>
        </div>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"></script>
</body>

</html>

<!-- Credit to https://epicbootstrap.com/snippets/footer-dark -->
    </div>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", required: false)
@RenderSection("upload", required: false)
@Scripts.Render("~/bundles/modernizr")
<!-- Bootstrap core JS-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
<!-- Core theme JS-->
<script src="js/scripts.js"></script>
</body>
</html>

ShopAcc/Views/Shared/_LayoutAdmin.cshtml
@{
    ViewBag.Title = "_LayoutAdmin";
}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @Scripts.Render("~/bundles/modernizr")
    <title>Admin Shop Acc</title>

    <!-- Custom fonts for this template-->
    <link href="~/Content/admin/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Custom styles for this template-->
    <link href="~/Content/admin/css/sb-admin-2.min.css" rel="stylesheet">
    <link href="~/Content/stylefooter.css" rel="stylesheet" />
</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="@Url.Action("Index1")">
                <div>
                    
                    <img src="~/Content/images/logoshop1.jpg"  width="120px" height="60px" alt="Logo Shop" />
                </div>
                <div class="sidebar-brand-text mx-3">Quản lý ShopAcc</div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                Chức năng
            </div>

            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
                   aria-expanded="true" aria-controls="collapseTwo">
                    <i class="fas fa-fw fa-folder"></i>
                    <span>Account</span>
                </a>
                <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <h6 class="collapse-header">Tính năng:</h6>
                        <a class="collapse-item" href="@Url.Action("Create")">Tạo Account mới</a>
                        <a class="collapse-item" href="@Url.Action("Index")">Tùy chỉnh Account</a>
                    </div>
                </div>
            </li>
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                Addons
            </div>
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("TTUser")">
                    <i class="fas fa-fw fa-table"></i>
                    <span>Người Dùng</span>
                </a>
            </li>
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                Addons
            </div>
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("TTHD")">
                    <i class="fas fa-fw fa-table"></i>
                    <span>Đơn Hàng</span>
                </a>
            </li>
            <hr class="sidebar-divider">
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("DangXuat","User")">
                    <i class="fas fa-fw fa-table"></i>
                    <span>Đăng Xuất</span>
                </a>
            </li>
            <!-- Divider -->
            <hr class="sidebar-divider">



            <!-- Divider -->
            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>



        </ul>
        <!-- End of Sidebar -->
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                </nav>
                <!-- End of Topbar -->
                <!-- Begin Page Content -->
                <div class="container-fluid">

                    @RenderBody()

                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->
            <!-- Footer -->
            <div class="footer-dark">
                <footer>
                    <div class="container">
                        <div class="row">
                            <div class="col-sm-6 col-md-3 item">
                                <h3 style="color:coral">&ensp;&emsp;<i class="bi bi-person-circle"></i> Morphine Deadline</h3>
                                <ul>
                                    <li><h6 style="font-size:small">&emsp;&emsp;Nguyễn Bùi Hoàng Phước</hr></li>
                                    <li><h6 style="font-size:small">&emsp;&emsp;Trần Thanh Phước</hr></li>
                                    <li><h6 style="font-size:small">&emsp;&emsp;Lê Trọng Phước</hr></li>
                                    <li><h6 style="font-size:small">&emsp;&emsp;Trần Hữu Quang</hr></li>
                                </ul>
                            </div>
                            <div class="col-sm-6 col-md-3 item">
                                <h3 style="color:coral">Liên Hệ:</h3>
                                <ul>
                                    <li><h6 style="font-size:smaller"><i class="bi bi-envelope-fill"></i>&ensp; shopaccvng@gmail.com</hr></li>
                                    <li><h6 style="font-size:smaller"><i class="bi bi-telephone-fill"></i>&ensp; 0788-988-797</hr></li>
                                    <li style="font-size:large; color:deepskyblue">
                                        &emsp;&emsp;<a href="https://www.facebook.com/profile.php?id=100005414179219"><i class="icon ion-social-facebook"></i> </a>&ensp;<a href="#"><i class="icon ion-social-twitter"></i></a>&ensp;<a href="#"> </a><a href="#"><i class="icon ion-social-instagram"></i> </a>
                                    </li>
                                </ul>
                            </div>
                            <div class="col-sm-6 col-md-6 item">
                                <div class="col-md-6 item text">
                                    <h3 style="color:coral">HUTECH - Khoa CNTT</h3>
                                    <p>Đồ án môn: Lập Trình Web</p>
                                    <p>Giảng viên hướng dẫn: Trịnh Công Nhựt</p>
                                    <p>Nhóm thực hiện: Nhóm 11</p>
                                </div>

                            </div>
                            @*<p class="copyright">Company Name © 2018</p>*@
                        </div>
                </footer>
            </div>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"></script>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="login.html">Logout</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="~/Content/admin/vendor/jquery/jquery.min.js"></script>
    <script src="~/Content/admin/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="~/Content/admin/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/Content/admin/js/sb-admin-2.min.js"></script>

    <!-- Page level plugins -->
    <script src="~/Content/admin/vendor/chart.js/Chart.min.js"></script>

    <!-- Page level custom scripts -->
    <script src="~/Content/admin/js/demo/chart-area-demo.js"></script>
    <script src="~/Content/admin/js/demo/chart-pie-demo.js"></script>


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    @RenderSection("upload", required: false)
</body>

</html>