ShopAcc/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ShopAcc.Models;
using ShopAcc.Mail;
using Newtonsoft.Json.Linq;
using ShopAcc.MoMo;
using System.Configuration;

namespace ShopAcc.Controllers
{
    public class CartController : Controller
    {
        // GET: Cart
        MyDataDataContext data = new MyDataDataContext();
        public List<GioHang> Laygiohang()
        {

            List<GioHang> lstGiohang = new List<GioHang>();
            User user = (User)Session["TaiKhoan"];
            var truycap = data.TruyCaps.Where(p => p.iduser == user.iduser && p.Account.trangthai==true);
            foreach (var item in truycap)
            {
                GioHang sanpham = new GioHang(item.id);
                lstGiohang.Add(sanpham);
            }
            ViewBag.Tongsoluong = lstGiohang.Count;
            ViewBag.Tongtien = lstGiohang.Sum(n => n.giaban);
            return lstGiohang;
        }
        public ActionResult ThemGioHang(int id, string strURL)
        {
            User user = (User)Session["TaiKhoan"];
            var acc = data.TruyCaps.Where(p => p.id == id && p.iduser ==user.iduser).FirstOrDefault();
            if (acc == null)
            {
                List<GioHang> lstGiohang = new List<GioHang>();
                TruyCap truyCap = new TruyCap();
                truyCap.iduser = user.iduser;
                truyCap.id = id;
                truyCap.trangthai = true;
                data.TruyCaps.InsertOnSubmit(truyCap);
                data.SubmitChanges();
                return Redirect(strURL);
            }
            else
                return Redirect(strURL);
        }
       
        public ActionResult GioHang()
        {
            List<GioHang> lstGiohang = Laygiohang();
            ViewBag.Tongsoluong = lstGiohang.Count;
            ViewBag.Tongtien = lstGiohang.Sum(n => n.giaban);
            return View(lstGiohang);
        }
        public ActionResult GioHangPartial()
        {
            return PartialView();
        }
        public ActionResult XoaAcc(int id)
        {
            List<GioHang> lstGiohang = Laygiohang();
            User user = (User)Session["TaiKhoan"];
            var truycap = data.TruyCaps.Where(p => p.id == id && p.iduser==user.iduser).First();
            if (truycap != null)
            {
                data.TruyCaps.DeleteOnSubmit(truycap);
                data.SubmitChanges();
            }

            return RedirectToAction("GioHang");

        }
        public ActionResult XoaAll()
        {

            User user = (User)Session["TaiKhoan"];

            var truycap = data.TruyCaps.Where(p => p.iduser == user.iduser);
            foreach (var item in truycap)
            {
                data.TruyCaps.DeleteOnSubmit(item);
            }
            data.SubmitChanges();

            return RedirectToAction("GioHang");
        }



        [HttpGet]
        public ActionResult DatHang()
        {
            List<GioHang> lstGiohang = Laygiohang();
            ViewBag.Tongsoluong = lstGiohang.Count;
            ViewBag.Tongtien = lstGiohang.Sum(n => n.giaban);
            if (lstGiohang == null )
            {
                return RedirectToAction("HomePage", "Account");
            }
           
            return View(lstGiohang);
        }
       
        //public ActionResult Payment()
        //{
        //    var lstGioHang = Laygiohang();
        //    User user = (User)Session["TaiKhoan"];
        //    var total = lstGioHang.Sum(n => n.giaban);

        //     string detail = "";

        //    foreach (var item in lstGioHang)
        //    {
        //        detail += "Tài khoản:  " + item.taikhoan.ToString() + "" + "Mật khẩu:  " + item.matkhau.ToString() + "=======================";
                
        //    }

        //    string content = System.IO.File.ReadAllText(Server.MapPath("~/content/template/neworder.html"))+detail;

        //    content = content.Replace("{{CustomerName}}", user.tenhienthi);
        //    content = content.Replace("{{Phone}}", user.sdt);
        //    content = content.Replace("{{Email}}", user.email);
        //    content = content.Replace("{{Address}}", user.anhdaidien);
        //    content = content.Replace("{{Total}}", total.ToString("N0"));
        //    var toEmail = ConfigurationManager.AppSettings["ToEmailAddress"].ToString();

            
        //    new MailHelper().SendEmail(user.email, "Xác nhận mua Acc", content);
        //    new MailHelper().SendEmail(toEmail, "Xác nhận mua Acc", content);
        //    return RedirectToAction("GioHang");

        //}
        //public ActionResult Payment()
        //{
        //    var lstGioHang = Laygiohang();
        //    User user = (User)Session["TaiKhoan"];
        //    var total = lstGioHang.Sum(n => n.giaban);

        //    string detail = "";

        //    foreach (var item in lstGioHang)
        //    {
        //        detail += "Tài khoản:  " + item.taikhoan.ToString() + "" + "Mật khẩu:  " + item.matkhau.ToString() + "=======================";

        //    }

        //    string content = System.IO.File.ReadAllText(Server.MapPath("~/content/template/neworder.html")) + detail;


        //    var hoadon = new HoaDon();
        //    hoadon.ngaythanhtoan = DateTime.Today;
        //    hoadon.thanhtoan = false;
        //    hoadon.tongtien = (Decimal)total;
        //    try
        //    {
        //        data.HoaDons.InsertOnSubmit(hoadon);
        //        data.SubmitChanges();

        //        foreach (var item in lstGioHang)
        //        {
        //            var cthd = new ChiTietHD();
        //            cthd.iduser = user.iduser;
        //            cthd.id = item.idacc;
        //            cthd.maHD = hoadon.maHD;
        //            cthd.gia = item.giaban;

        //            data.ChiTietHDs.InsertOnSubmit(cthd);
        //            data.SubmitChanges();
        //        }

        //        //var chitiet = data.ChiTietHDs.ToList();
        //        //var acc = data.Accounts.ToList();
        //        content = content.Replace("{{CustomerName}}", user.tenhienthi);
        //        content = content.Replace("{{Phone}}", user.sdt);
        //        content = content.Replace("{{Email}}", user.email);
        //        content = content.Replace("{{Total}}", hoadon.tongtien.ToString());
        //        foreach (var item in lstGioHang)
        //        {
        //            content = content.Replace("{{TaiKhoan}}", item.taikhoan);
        //            content = content.Replace("{{MatKhau}}", item.matkhau);
        //        }
        //        var toEmail = ConfigurationManager.AppSettings["ToEmailAddress"].ToString();


        //        new MailHelper().SendEmail(user.email, "Xác nhận mua Acc", content);
        //        new MailHelper().SendEmail(toEmail, "Xác nhận mua Acc", content);
        //    }
        //    catch (Exception)
        //    {
        //        return Redirect("/Cart/UnSuccess");
        //    }
        //    return Redirect("/Cart/Success");
        //}
        public ActionResult PaymentMoMo()
        {
            var lstGioHang = Laygiohang();
            User user = (User)Session["TaiKhoan"];
            var total = lstGioHang.Sum(n => n.giaban);

            string detail = "";

            foreach (var item in lstGioHang)
            {
                detail += "Tài khoản:  " + item.taikhoan.ToString() + "------" + "Mật khẩu:  " + item.matkhau.ToString() + "=======================";

            }

            string content = System.IO.File.ReadAllText(Server.MapPath("~/content/template/neworder.html")) + detail;
            foreach (var item in lstGioHang)
            {
                var acc = data.Accounts.Where(p => p.id == item.idacc).First();
                if(acc!= null)
                {
                    acc.trangthai = false;
                    UpdateModel(acc);
                    data.SubmitChanges();

                }    
            }
           

            
            data.SubmitChanges();
            var hoadon = new HoaDon();
            hoadon.ngaythanhtoan = DateTime.Today;
            hoadon.thanhtoan = true;
            hoadon.tongtien = (Decimal)total;
            try
            {
                data.HoaDons.InsertOnSubmit(hoadon);
                data.SubmitChanges();

                foreach (var item in lstGioHang)
                {
                    var cthd = new ChiTietHD();
                    cthd.iduser = user.iduser;
                    cthd.id = item.idacc;
                    cthd.maHD = hoadon.maHD;
                    cthd.gia = item.giaban;

                    data.ChiTietHDs.InsertOnSubmit(cthd);
                    data.SubmitChanges();

                }
               
                //var chitiet = data.ChiTietHDs.ToList();
                //var acc = data.Accounts.ToList();
                content = content.Replace("{{CustomerName}}", user.tenhienthi);
                content = content.Replace("{{Phone}}", user.sdt);
                content = content.Replace("{{Email}}", user.email);
                content = content.Replace("{{Total}}", hoadon.tongtien.ToString());
                foreach (var item in lstGioHang)
                {
                    content = content.Replace("{{TaiKhoan}}", item.taikhoan);
                    content = content.Replace("{{MatKhau}}", item.matkhau);
                }
                var toEmail = ConfigurationManager.AppSettings["ToEmailAddress"].ToString();


                new MailHelper().SendEmail(user.email, "Xác nhận mua Acc", content);
                new MailHelper().SendEmail(toEmail, "Xác nhận mua Acc", content);
                
            }

            catch (Exception)
            {
                return Redirect("/Cart/UnSuccess");
            }


            //request params need to request to MoMo system

ShopAcc/Controllers/UserController.cs
using ShopAcc.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShopAcc.Controllers
{
    public class UserController : Controller
    {
        MyDataDataContext data = new MyDataDataContext();
        [HttpGet]
        public ActionResult DangKy()
        {
            return View();
        }
        [HttpPost]
        public ActionResult DangKy(FormCollection collection, User us)
        {
            var tendn = collection["tendn"];
            var matkhau = collection["matkhau"];
            var email = collection["email"];
            var MatKhauXacNhan = collection["MatKhauXacNhan"];
            var sdt = collection["sdt"];
            var tenhienthi = collection["tenhienthi"];
            var anhdaidien = collection["anhdaidien"];
            var trangthai = Convert.ToBoolean(collection["trangthai"]);
            User checktendn = data.Users.SingleOrDefault(n => n.tendn == tendn);
            Admin checkadmin = data.Admins.SingleOrDefault(n => n.tenDangNhap == tendn && n.matkhau == matkhau);
            if (String.IsNullOrEmpty(tendn))
            {
                ViewData["Loi1"] = "Phải nhập tên đăng nhập!";
            }
            else if (String.IsNullOrEmpty(matkhau))
            {
                ViewData["Loi2"] = "Phải nhập mật khẩu!";
            }

            else if (String.IsNullOrEmpty(matkhau))
            {
                ViewData["Loi2"] = "Phải nhập mật khẩu!";
            }
            else if (String.IsNullOrEmpty(MatKhauXacNhan))
            {
                ViewData["NhapMKXN"] = "Phải nhập mật khẩu xác nhận!";
            }

            else if (String.IsNullOrEmpty(email))
            {
                ViewData["Loi3"] = "Phải nhập email!";
            }
            else if (String.IsNullOrEmpty(sdt))
            {
                ViewData["Loi4"] = "Phải nhập số điện thoại!";
            }
            else if (String.IsNullOrEmpty(tenhienthi))
            {
                ViewData["Loi5"] = "Phải nhập tên hiển thị!";
            }
            else if (String.IsNullOrEmpty(anhdaidien))
            {
                ViewData["Loi6"] = "Phải nhập ảnh đại diện!";
            }

            else
            {
                if (checkadmin != null)
                {
                    ViewBag.ThongBao = "Tên đăng nhập đã tồn tại";
                }
                else if (checktendn != null)
                {
                    ViewBag.ThongBao = "Tên đăng nhập đã tồn tại";
                }
                else
                {
                    if (!matkhau.Equals(MatKhauXacNhan))
                    {
                        ViewData["MatKhauGiongNhau"] = "Mật khẩu và mật khẩu xác nhận phải giống nhau";
                    }
                    else
                    {
                        us.tendn = tendn;
                        us.matkhau = matkhau;
                        us.email = email;
                        us.sdt = sdt;
                        us.tenhienthi = tenhienthi;
                        us.anhdaidien = anhdaidien.ToString();
                        us.trangthai = true;

                        data.Users.InsertOnSubmit(us);
                        data.SubmitChanges();
                        return RedirectToAction("DangNhap");
                    }
                }
            }

            return this.DangKy();
        }
        public string ProcessUpload(HttpPostedFileBase file)
        {
            if (file == null)
            {
                return "";
            }
            file.SaveAs(Server.MapPath("~/Content/images/" + file.FileName));
            return "/Content/images/" + file.FileName;
        }

        [HttpGet]
        public ActionResult DangNhap()
        {
            return View();
        }
        [HttpPost]
        public ActionResult DangNhap(FormCollection collection)
        {
            var tendn = collection["tendn"];
            var matkhau = collection["matkhau"];
            if (String.IsNullOrEmpty(tendn))
            {
                ViewData["Loi1"] = "Phải nhập tên đăng nhập!";
            }
            if (String.IsNullOrEmpty(matkhau))
            {
                ViewData["Loi2"] = "Phải nhập mật khẩu!";
            }
            User us = data.Users.SingleOrDefault(n => n.tendn == tendn && n.matkhau == matkhau && n.trangthai==true);
            Admin checkadmin = data.Admins.SingleOrDefault(n => n.tenDangNhap == collection["tendn"] && n.matkhau == collection["matkhau"]);
            if (us != null)
            {
                
                ViewBag.ThongBao = "Chúc mừng đăng nhập thành công";
                Session["TaiKhoan"] = us;

                return RedirectToAction("HomePage", "Account");
            }
            else if(checkadmin != null)
            {

                ViewBag.ThongBao = "Chúc mừng đăng nhập thành công";
                Session["TaiKhoan"] = checkadmin;

                return RedirectToAction("Index1", "Admin");
                
            }
            else
            {
                ViewBag.ThongBao = "Tên đăng nhập hoặc mật khẩu không đúng";
            }
            return View();
        }
        [HttpGet]
        public ActionResult DangXuat()
        {
            Session.Clear();
            return RedirectToAction("HomePage","Account");
        }
        [HttpGet]
        public ActionResult Edit(int? id)
        {
            User find = data.Users.FirstOrDefault(p => p.iduser == id);
            return View(find);
        }

        [HttpPost]
        public ActionResult Edit(FormCollection collection, int id)
        {
            var s = data.Users.First(m => m.iduser == id);

            var matkhau = collection["matkhau"];
            var email = collection["email"];
           
            var sdt = collection["sdt"];
            var tenhienthi = collection["tenhienthi"];
            var anhdaidien = collection["anhdaidien"];
            
          

            if (String.IsNullOrEmpty(matkhau))
            {
                ViewData["Loi2"] = "Phải nhập mật khẩu!";
            }
           

            else if (String.IsNullOrEmpty(email))
            {
                ViewData["Loi3"] = "Phải nhập email!";
            }
            else if (String.IsNullOrEmpty(sdt))
            {
                ViewData["Loi4"] = "Phải nhập số điện thoại!";
            }
            else if (String.IsNullOrEmpty(tenhienthi))
            {
                ViewData["Loi5"] = "Phải nhập tên hiển thị!";
            }
            else if (String.IsNullOrEmpty(anhdaidien))
            {
                ViewData["Loi6"] = "Phải nhập ảnh đại diện!";
            }
                else
                {
                    s.matkhau = matkhau;
                    s.email = email;
                    s.sdt = sdt;
                    s.tenhienthi = tenhienthi;
                    s.anhdaidien = anhdaidien.ToString();
                        UpdateModel(s);
                        data.SubmitChanges();
                        return RedirectToAction("DangNhap");
                }
            return View(id);
            }
    }
}

ShopAcc/Views/Game/LMHT.cshtml
@model IEnumerable<ShopAcc.Models.Account>

@{
    ViewBag.Title = "LMHT";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Liên Minh Huyền Thoại</h2>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>ShopAcc</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <!-- Bootstrap icons-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>

    <!-- Core theme CSS (includes Bootstrap)-->

    <link href="~/Content/Style.css" rel="stylesheet" />
</head>
<body>
    <section class="py-5">
        <div class="container px-4 px-lg-5 mt-5">

            <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                @foreach (var item in Model)
                {
                    <div class="col mb-5">

                        <div class="card h-100">
                            <!-- Product image-->
                            <div class="badge bg-danger text-black position-absolute" style="top: 0.5rem; right: 0.5rem">#@item.id</div>

                            <img class="card-img-top" src="@item.hinh" width="100%" height="150px" alt="..." />
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <div class="panel" style="background-color: darkgrey">
                                        <h5 class="fw-bolder">@item.LoaiGame.tengame</h5>
                                    </div>

                                    <!-- Product reviews-->
                                    <!-- Product price-->

                                </div>
                                <div class="text-left">
                                    <strong>
                                        Rank : @item.rank
                                        <p> </p>
                                    </strong>
                                    <strong>
                                        Tướng : @item.tuong
                                        <p> </p>
                                    </strong><strong>
                                        Trang phục : @item.trangphuc
                                        <p> </p>
                                    </strong>

                                    <strong>
                                        Giá:
                                        <span class="text-muted text-decoration-line-through">@String.Format("{0:0,0đ}", item.giaban.Value + 30000)</span>
                                        <label><i class="bi bi-arrow-right"></i></label>
                                        @String.Format("{0:0,0đ}", item.giaban.Value)
                                    </strong>
                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-info mt-auto" style="width: 220px" href="@Url.Action("Detail", "Account", new { @id = item.id, @strURL = Request.Url.ToString() })"><strong>Vô coi chơi nè...&nbsp;</strong><i class="bi bi-emoji-heart-eyes-fill"></i></a></div>
                            </div>
                            @if (User != null)
                            {
                                <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                    <div class="text-center"><a class="btn btn-danger mt-auto" style="width: 220px" href="@Url.Action("Themgiohang", "Cart", new { @id = item.id, @strURL = Request.Url.ToString() })"><i class="bi bi-cart-plus"></i> <strong>&nbsp;Thêm vào giỏ hàng</strong></a></div>
                                </div>
                            }
                            else
                            {

                                <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                    <div class="text-center"><a class="btn btn-danger mt-auto" style="width: 220px" href="@Url.Action("DangNhap", "User", new { @id = item.id, @strURL = Request.Url.ToString() })"><i class="bi bi-cart-plus"></i> <strong>&nbsp;Thêm vào giỏ hàng</strong></a></div>
                                </div>
                            }

                        </div>
                    </div>
                }
            </div>
        </div>
    </section>
</body></table>

ShopAcc/Views/Game/LQM.cshtml
@model IEnumerable<ShopAcc.Models.Account>

@{
    ViewBag.Title = "LQM";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Liên Quân Mobile</h2>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>ShopAcc</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <!-- Bootstrap icons-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>

    <!-- Core theme CSS (includes Bootstrap)-->

    <link href="~/Content/Style.css" rel="stylesheet" />
</head>
<body>
    <section class="py-5">
        <div class="container px-4 px-lg-5 mt-5">

            <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                @foreach (var item in Model)
                {
                    <div class="col mb-5">

                        <div class="card h-100">
                            <!-- Product image-->
                            <div class="badge bg-danger text-black position-absolute" style="top: 0.5rem; right: 0.5rem">#@item.id</div>

                            <img class="card-img-top" src="@item.hinh" width="100%" height="150px"  alt="..." />
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <div class="panel" style="background-color: darkgrey">
                                        <h5 class="fw-bolder">@item.LoaiGame.tengame</h5>
                                    </div>

                                    <!-- Product reviews-->
                                    <!-- Product price-->

                                </div>
                                <div class="text-left">
                                    <strong>
                                        Rank : @item.rank
                                        <p> </p>
                                    </strong>
                                    <strong>
                                        Tướng : @item.tuong
                                        <p> </p>
                                    </strong><strong>
                                        Trang phục : @item.trangphuc
                                        <p> </p>
                                    </strong>

                                    <strong>
                                        Giá:
                                        <span class="text-muted text-decoration-line-through">@String.Format("{0:0,0đ}", item.giaban.Value + 30000)</span>
                                        <label><i class="bi bi-arrow-right"></i></label>
                                        @String.Format("{0:0,0đ}", item.giaban.Value)
                                    </strong>
                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-info mt-auto" style="width: 220px" href="@Url.Action("Detail", "Account", new { @id = item.id, @strURL = Request.Url.ToString() })"><strong>Vô coi chơi nè...&nbsp;</strong><i class="bi bi-emoji-heart-eyes-fill"></i></a></div>
                            </div>
                            @if (User != null)
                            {
                                <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                    <div class="text-center"><a class="btn btn-danger mt-auto" style="width: 220px" href="@Url.Action("Themgiohang", "Cart", new { @id = item.id, @strURL = Request.Url.ToString() })"><i class="bi bi-cart-plus"></i> <strong>&nbsp;Thêm vào giỏ hàng</strong></a></div>
                                </div>
                            }
                            else
                            {

                                <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                    <div class="text-center"><a class="btn btn-danger mt-auto" style="width: 220px" href="@Url.Action("DangNhap", "User", new { @id = item.id, @strURL = Request.Url.ToString() })"><i class="bi bi-cart-plus"></i> <strong>&nbsp;Thêm vào giỏ hàng</strong></a></div>
                                </div>
                            }

                        </div>
                    </div>
                }
            </div>
        </div>
    </section>
</body>